export const CSS_VARIABLES_ASSISTANT_JETBRAINS_PLUGIN_ID = 27392;
export const PLUGIN_ID_CARD = `CARD_${CSS_VARIABLES_ASSISTANT_JETBRAINS_PLUGIN_ID}`;
export const PLUGIN_ID_INSTALL = `INSTALL_${CSS_VARIABLES_ASSISTANT_JETBRAINS_PLUGIN_ID}`;
